# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctguard < Formula
  desc "Detect timing side-channel vulnerabilities in Go code"
  homepage "https://github.com/oasilturk/ctguard"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.10.0/ctguard_0.10.0_darwin_amd64.tar.gz"
      sha256 "c5f21187859e97d23512fb87aed1c36b454f6b19bdfd0d51959022dd9b11c41d"

      define_method(:install) do
        bin.install "ctguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.10.0/ctguard_0.10.0_darwin_arm64.tar.gz"
      sha256 "c905aba0a05a289cf05217556b73ba314fc95eb76e03179c81a926f45ae65007"

      define_method(:install) do
        bin.install "ctguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.10.0/ctguard_0.10.0_linux_amd64.tar.gz"
      sha256 "79191c68c54faa6692133e50c143abeff5d71ab29f31d3bee757eaaa0d43c39a"
      define_method(:install) do
        bin.install "ctguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.10.0/ctguard_0.10.0_linux_arm64.tar.gz"
      sha256 "2a38989867cc2389144f0b0a703bd435d8238f8cceacdf69d80c00bf6ba9711b"
      define_method(:install) do
        bin.install "ctguard"
      end
    end
  end
end
