# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctguard < Formula
  desc "Detect timing side-channel vulnerabilities in Go code"
  homepage "https://github.com/oasilturk/ctguard"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.9.0/ctguard_0.9.0_darwin_amd64.tar.gz"
      sha256 "e8f491d151af3c84dea645b01e39200afa193bfeb20aa147751621ec4090a68d"

      define_method(:install) do
        bin.install "ctguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.9.0/ctguard_0.9.0_darwin_arm64.tar.gz"
      sha256 "fc8b23eae3fbff7129747f0cacda9c5055b63ab88ec5ced9999bc1122649e6b8"

      define_method(:install) do
        bin.install "ctguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.9.0/ctguard_0.9.0_linux_amd64.tar.gz"
      sha256 "a1c8b0c3cca8e07ba8ec3863588e5f6ee99654d0e6905b88f65308753a4f6380"
      define_method(:install) do
        bin.install "ctguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasilturk/ctguard/releases/download/v0.9.0/ctguard_0.9.0_linux_arm64.tar.gz"
      sha256 "47561e21bd07fa72455d52307a3ccf89e4e25081a02449d04459539a988696e8"
      define_method(:install) do
        bin.install "ctguard"
      end
    end
  end
end
